# Generated by Django 5.1.7 on 2025-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_account_created_at_alter_account_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="role",
        ),
        migrations.AddField(
            model_name="account",
            name="role_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Student"),
                    (2, "Tutor"),
                    (3, "Freelancer"),
                    (4, "Mentor"),
                ],
                default=1,
            ),
        ),
    ]
