# Generated by Django 5.2.7 on 2026-01-11 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_options_remove_job_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="mode",
        ),
    ]
