repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
#        args: ["c", "pyproject.toml"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
#      - id: ruff-check
      - id: ruff-format
-   repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
#      - id: djlint-django
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.18.2
#    hooks:
#      - id: mypy
#        args: [ --ignore-missing-imports ]