# Generated by Django 5.1.7 on 2025-08-10 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_remove_listing_location_alter_listing_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="listing",
            name="status",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="rate_unit",
            field=models.CharField(
                choices=[("hourly", "per hour"), ("fixed", "fixed")],
                default="hourly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="subject",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[("tutor", "Tutor"), ("mentor", "Mentor")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
