# Generated by Django 5.1.7 on 2025-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_options_remove_listing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[("tutor", "Tutor"), ("mentor", "Mentor")],
                default="tutor",
                max_length=10,
            ),
        ),
    ]
