# Generated by Django 5.2.7 on 2025-10-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_all_availabilities(apps, schema_editor):
    Availability = apps.get_model('listings', 'Availability')
    Availability.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_max_hours_per_booking_availability_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_all_availabilities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='availability',
            name='listing',
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='availabilities',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
