# Generated by Django 5.2.7 on 2026-01-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="student_marked_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="tutor_marked_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="listings.booking",
            ),
        ),
    ]
