# Generated by Django 5.2.7 on 2026-01-17 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_booking_student_marked_complete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="max_hours_per_booking",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="rate_unit",
        ),
    ]
