# Generated by Django 5.2.7 on 2025-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="role_at_time",
            field=models.IntegerField(
                choices=[
                    (1, "Student"),
                    (2, "Tutor"),
                    (3, "Freelancer"),
                    (4, "Mentor"),
                ],
                default=1,
            ),
        ),
    ]
